services:
    auth-service:
        container_name: auth-service
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env.production.local
        expose:
            - "9101"
        volumes:
            - ../logs:/var/log/services/auth/
        networks:
            - kirt08

networks:
    kirt08:
        external: true